### ISSUE TITLE
 Vaccinator wrongly registered my date of birth 

### ISSUE THREAD

**Issue by kaushickmehta** [benjithorpe/benjithorpe.github.io#1]
I vaccinated on spot registeration in vaccination centre. the vaccinator wrongly registered my date of birth.I getting certificate but age is different .how to correct this problems? this is looking like fake certificate and may be problem travel time. how to correct this.

**Comment by benjithorpe** [comment]
Sorry, but I don't really know how to do those.
And also, please this was not the correct place to send it. Thanks
